### ISSUE TITLE
core dumped ramme

### ISSUE THREAD

**Issue by EngMjari** [terkelg/ramme#321]
╰─➤  ramme
[1]    15906 segmentation fault (core dumped)  ramme
 what is this Error ?

**Comment by marco-fp** [comment]
Having the same issue, Linux (Ubuntu 18)

**Comment by hulkpk** [comment]
OLD version works fine

**Comment by hulkpk** [comment]
No idea :P

**Comment by carestad** [comment]
Seems to only happen in 3.2.5. 3.2.3 works as far as I can tell

**Comment by orangecoloured** [comment]
Getting this in mac build
```
Uncaught Exception:
Error: ENOENT, dist/renderer/styles/app.css not found in /Applications/Ramme.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:114:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:518:9)
    at WebContents.page.on (/Applications/Ramme.app/Contents/Resources/app.asar/src/main/index.js:156:23)
    at emitOne (events.js:116:13)
    at WebContents.emit (events.js:211:7)
```

The app works thought.
