### ISSUE TITLE
How to make it ? 

### ISSUE THREAD

**Issue by xxiloa** [terkelg/ramme#97]
Hi, 
I run opensuse linux leap 42.2. 
it don't work. this is return :

```
> @ build /home/xxiloa/Telechargements/ramme
> gulp build

[12:20:16] Failed to load external module babel-register
[12:20:16] Failed to load external module babel-core/register
[12:20:16] Failed to load external module babel/register
/home/xxiloa/Telechargements/ramme/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import {src, dest, watch as watchSrc, parallel, series} from 'gulp'
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at execute (/home/xxiloa/Telechargements/ramme/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:35:18)
    at Liftoff.handleArguments (/home/xxiloa/Telechargements/ramme/node_modules/gulp/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/home/xxiloa/Telechargements/ramme/node_modules/gulp/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)

npm ERR! Linux 4.4.36-8-default
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! @ build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'gulp build'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxiloa/Telechargements/ramme/npm-debug.log
```

**Comment by anatolinicolae** [comment]
I'll add a quick guide to build it some time.

Anyway, it's just few steps to follow.

First, install app's deps:
```
cd app && npm install && cd ..
```
Then install main package deps:
```
npm install
```
Then run the build:
```
npm run build
```

Make sure to run these commands from the dir where you cloned Ramme into. If you get an error, try `sudo`ing or give up.
